sudo: required
services:
  - docker

before_install:
  - docker build -t myimage -f Dockerfile.dev .

script:
  - docker run myimage npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-751592947820"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secreat_access_key:
    secure: $AWS_SECRET_KEY
